UComment/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'UComment'
urlpatterns = [
    url(r'^profile/(?P<slug>\w+)/$', login_required(views.UserView.as_view(), login_url='music:index'), name='user'),
]

music/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'music'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),  # conexion con el index
    url(r'configuration/$', views.ConfigView, name = 'config'),  # pagina de configuracion
#    url(r'signup/$',views.SignView.as_view(),name = 'signup'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view(), login_url='music:index'), name='detail'),  # conexion con el view de detalles del album
    url(r'album/add/$', login_required(views.AlbumCreate.as_view(), login_url='music:index'), name='album-add'),  # creacion de un nuevo album

     #para hacer un update se necesita ir tld/app/album/pk/
    url(r'album/(?P<pk>[0-9]+)/$', login_required(views.AlbumUpdate.as_view(), login_url='music:index'), name='album-update'), #actualizar un album
    url(r'album/(?P<pk>[0-9]+)/delete/$', login_required(views.AlbumDelete.as_view(), login_url='music:index'), name='album-delete'), #eliminar un album entero
    #url(r'register/$',views.RegisterView.as_view(),name='register'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', login_required(views.create_song, login_url='music:index'), name='create_song'), #crear cancion
    url(r'song/(?P<pk>[0-9]+)/delete/$', login_required(views.SongDelete.as_view(), login_url='music:index'), name='song-delete'), #eliminar una cancion
    url(r'^(?P<song_id>[0-9]+)/favorite/$', login_required(views.favorite,login_url='music:index'), name='favorite'),#favoritear un cancion
    url(r'^(?P<album_id>[0-9]+)/favorite_album/$', login_required(views.favorite_album, login_url='music:index'), name='favorite_album'),#favoritear un album
    ]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import privacy, helpi, license

urlpatterns = [
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music.urls')),
    url(r'^', include('UComment.urls')),
    url(r'^privacy/$', privacy, name='privacy'),
    url(r'^help/$', helpi, name='help'),
    url(r'^license/$', license, name='license'),
]

if settings.DEBUG:
    ##urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UComment/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.core.urlresolvers import reverse
#from django_markdown.models import MarkdownField


# Create your models here.

#userinfo Model
class UserInfo(models.Model):
    user = models.ForeignKey(User)
    Fname = models.CharField(max_length=500)
    Lname = models.CharField(max_length=500)
    ImageUser = models.FileField()
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.user.get_username()


class Comments(models.Model):
    user = models.ForeignKey(User)
    Ucomen = models.CharField(max_length=500)
    content = models.CharField(max_length=500)
    created = models.DateField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.user.get_username()



# #modelo del album
# class Album(models.Model):
#         user = models.ForeignKey(User, default=1)
#         artist = models.CharField(max_length=250)
#         album_title = models.CharField(max_length=500)
#         genre = models.CharField(max_length=100)
#         album_logo = models.FileField()
#         is_favorite  = models.BooleanField(default=False)
#
#         def get_absolute_url(self):
#             return reverse('music:detail',kwargs={'pk': self.pk})
#
#         def __str__(self):
#             return self.album_title + ' - ' +self.artist

music/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.

# modelo del album
class Album(models.Model):
    user = models.ForeignKey(User, default=1)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


# modelo de la cancion
class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    audio_file = models.FileField(default='')
    song_title = models.CharField(max_length=250)
    is_favority = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

UComment/views.py
from django.contrib.auth.models import User
from django.views import generic
from .models import UserInfo, Comments
from music.models import Album, Song


# Create your views here.

class UserView(generic.DetailView):
    model = User
    slug_field = "username"
    template_name = "UComment/bio.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context

        context = super(UserView, self).get_context_data(**kwargs)

        # Agregar los contextos necesarios
        context['username'] = self.object.get_username()
        user = UserInfo.objects.filter(user=self.object)
        # print(user[0])
        coment = Comments.objects.filter(user=self.object)
        albums = Album.objects.filter(user=self.object)
        # print(coment)

        context['user'] = user[0]
        context['comments'] = coment
        context['albums'] = albums
        # context['songs'] = Song.objects.filter(album=Album.objects.filter(user=self.object))
        context['lalbums'] = len(albums)

        conti = 0
        for album in albums:
            cont = Song.objects.filter(album=album)
            conti += len(cont)

        context['lsongs'] = conti
        # print( Album.objects.filter(user=self.object))

        return context

templates/UComment/bio.html
{% extends "base.html" %}
{% block title %}Biografia{% endblock %}
{% load staticfiles %}
{% block content %}


{% for album in albums  %}
{% for song in album.song_set.all %}
<Audio id="{{ song.audio_file.url }}" ontimeupdate="timeFunct('{{ song.audio_file.url }}')" preload="none">
  <source src="{{ song.audio_file.url }}" type="audio/mp3">
</Audio>
{% endfor %}
{% endfor %}

  <!--AQUI COMIENZA-->
  <dir class="container" style="margin-bottom: 140px;">
    <div class="jumbotron">
      <img src="{{user.ImageUser.url}}" class="img-circle" style="min-width: 170px; max-width: 170px; max-height: 170px; min-height: 170px; float: left; margin-right: 50px;">
        <h2><span class="label label-default">@{{username}}</span></h2> <!--nombre de usuario-->
        <p class="text-muted">{{user.description}}<br><br><br></p>
    </div>

      <!--SEPARADOR-->
  <ul class="nav nav-tabs" style="background-color: #eee;">
    <li class="active"><a data-toggle="tab" href="#home">Discografia <span class="badge">{{lalbums}}</span></a></li>
    <li><a data-toggle="tab" href="#menu1">Canciones <span class="badge">{{lsongs}}</span></a></a></li>
    <li><a data-toggle="tab" href="#menu2">Comentarios</a></li>
  </ul>

  <div class="tab-content">

    <div id="home" class="tab-pane fade in active"><!--tab-pane fade in active-->
      <br>
      <br>
      <div class="container">
        <div class="row">
          {% for album in albums %}
          <a href="{% url 'music:detail' album.id %}" style="display: inline;">
            <div class="col-xs-6 col-sm-4 col-lg-2 placeholder">
              <img class="img-responsive img-rounded" src="{{ album.album_logo.url }}"
              style="min-width: 150px; max-width: 150px; max-height: 150px; min-height: 150px;">
                <span class="optionsBar">
                  {# funcion para favoritear #}
                  <a href="{% url 'music:favorite_album' album.id %}" role="button" style="text-decoration: none;">
                    <button id="heart" class="btn btn-default glyphicon {% if album.is_favorite %}glyphicon-heart{% else %}glyphicon-heart-empty{% endif %}" style="margin-left: 4px;"></button>
                  </a>
                  {% if album.user == user %}
                      {# funcion para eliminar los albums #}
                  <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                      {% csrf_token %}
                      <input type="hidden" name="album_id" value="{{ album.id }}"/>
                        <button type="submit" id="trash" class="btn btn-default glyphicon glyphicon-trash"></button>
                  </form>

                  {% endif %}

                  {# funcion para entrar en los detalles del album#}
                  <a href="{% url 'music:detail' album.id %}" style="text-decoration: none">
                      <button id="option" class="btn btn-default glyphicon glyphicon-option-horizontal"></button>
                  </a>
                </span>
            </div>
          </a>
          {% endfor %}
        </div>
    </div>
    </div>


    <div id="menu1" class="tab-pane fade">
          <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <h3>Canciones</h3>
            </div>
          <div class="col-sm-12">
            <div class="panel panel-default">
              <div class="panel-body">
                <table class="table">
                  <thead>
                    <tr>
                    <th> </th>
                    <th>Título</th>
                    <th>Artista</th>
                    <th>Álbum</th>
                    <th>Favorito</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for album in albums  %}
                  {% for song in album.song_set.all %}
                    <tr>
                    <td>
                    <button id="list_play" type="button" class="btn btn-link btn-xs" style="text-decoration: none;" onclick="play_funct_aux('{{ song.audio_file.url }}', '{{ album.album_logo.url }}', '{% static 'img/album.png' %}', '{{ song.song_title }}', '{{ song.album.artist }}', '{{ song.album.album_title }}')">
                      <span class="glyphicon glyphicon-play" style="color: #222;"></span>
                    </button>
                    </td>

                    <td>{{ song.song_title }}</td>
                    <td>{{ song.album.artist }}</td>
                    
                    <td>
                    <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                      </td>
                      <td>
                    <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon {% if song.is_favority %}glyphicon-heart{% else %}glyphicon-heart-empty{% endif %}" style="color:  #222;"></span></a>
                    </td>
                    </tr>
                  {% endfor %}
                {% endfor %}
                </tbody>
                </table>
              </div>
            </div>
          </div>
          </div>
          </div>
    </div>


    <div id="menu2" class="tab-pane fade">
      <br>
      <p>
        {% for coment in comments %}
          <input class="form-control" type="text" placeholder="{{coment.content}}" disabled /><br>
        {% endfor %}
        <textarea class="form-control" rows="3" placeholder="Comentario"></textarea><br>
        <a class="btn btn-md btn-primary" href="#" role="button" style="float: right">Publicar <span class="glyphicon glyphicon-send" aria-hidden="true"></span></a>
      </p><br>
    </div>


  </div>
    <hr>
      <a class="btn btn-md btn-default" href="#" role="button" style="float: right">Modificar perfil <span class="glyphicon glyphicon-cog" aria-hidden="true" style="color: #000;"></span></a>
  </dir>

  <!--AQUI TERMINA-->


{% endblock %}