music/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'music'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),  # conexion con el index
    url(r'configuration/$', views.ConfigView, name = 'config'),  # pagina de configuracion
#    url(r'signup/$',views.SignView.as_view(),name = 'signup'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view(), login_url='music:index'), name='detail'),  # conexion con el view de detalles del album
    url(r'album/add/$', login_required(views.AlbumCreate.as_view(), login_url='music:index'), name='album-add'),  # creacion de un nuevo album

     #para hacer un update se necesita ir tld/app/album/pk/
    url(r'album/(?P<pk>[0-9]+)/$', login_required(views.AlbumUpdate.as_view(), login_url='music:index'), name='album-update'), #actualizar un album
    url(r'album/(?P<pk>[0-9]+)/delete/$', login_required(views.AlbumDelete.as_view(), login_url='music:index'), name='album-delete'), #eliminar un album entero
    #url(r'register/$',views.RegisterView.as_view(),name='register'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', login_required(views.create_song, login_url='music:index'), name='create_song'), #crear cancion
    url(r'song/(?P<pk>[0-9]+)/delete/$', login_required(views.SongDelete.as_view(), login_url='music:index'), name='song-delete'), #eliminar una cancion
    url(r'^(?P<song_id>[0-9]+)/favorite/$', login_required(views.favorite,login_url='music:index'), name='favorite'),#favoritear un cancion
    url(r'^(?P<album_id>[0-9]+)/favorite_album/$', login_required(views.favorite_album, login_url='music:index'), name='favorite_album'),#favoritear un album
    ]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import privacy, helpi, license

urlpatterns = [
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music.urls')),
    url(r'^', include('UComment.urls')),
    url(r'^privacy/$', privacy, name='privacy'),
    url(r'^help/$', helpi, name='help'),
    url(r'^license/$', license, name='license'),
]

if settings.DEBUG:
    ##urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.

# modelo del album
class Album(models.Model):
    user = models.ForeignKey(User, default=1)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


# modelo de la cancion
class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    audio_file = models.FileField(default='')
    song_title = models.CharField(max_length=250)
    is_favority = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Album, Song


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']

music/views.py
from django.views import generic
from .models import Album, Song
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .forms import AlbumForm, SongForm
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.contrib.auth.decorators import login_required

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


class IndexView(View):

    def get(self, request):
        if not request.user.is_authenticated():
            return render(request, "base1.html", {})
        else:
            albums = Album.objects.filter(user=request.user)
            song_results = Song.objects.all()
            query = request.GET.get("q")
            if query:
                albums = Album.objects.all()
                albums = albums.filter(
                    Q(album_title__icontains=query) |
                    Q(artist__icontains=query) |
                    Q(genre__icontains=query)
                ).distinct()
                song_results = song_results.filter(
                    Q(song_title__icontains=query)
                ).distinct()
                return render(request, 'music/index.html', {
                    'albums': albums,
                    'songs': song_results,
                    'user': request.user,
                    'username': request.user.get_username(),
                })
            else:
                return render(request, 'music/index.html', {
                    'albums': albums,
                    'username': request.user.get_username(),
                })


def ConfigView(request):
    if not request.user.is_authenticated():
        return redirect('music:index')
    else:
        return render(request, 'music/config.html', {'username': request.user.get_username()})


class RegisterView(View):
    def get(self, request):
        if request.user.is_authenticated():
            return redirect('music:index')
        else:
            return render(request, 'music/signup.html', {'username': request.user.get_username()})


# class DetailViews(View):
#     def get(self,request):
#         if  not request.user.is_authenticated():
#             return redirect('http://127.0.0.1:8000')
#         else:
#             user = request.user
#             album = get_object_or_404(Album, pk=album_id)
#             return render(request, 'music/detail.html', {'album': album, 'user': user} )


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(DetailView, self).get_context_data(**kwargs)
        context['username'] = self.object.user.get_username()

        return context


# Creates, Updates Y Deletes

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(AlbumCreate, self).get_context_data(**kwargs)
        # print(self.request.user.get_username())
        context['username'] = self.request.user.get_username()

        return context


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(AlbumUpdate, self).get_context_data(**kwargs)
        context['username'] = self.object.get_username()

        return context


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


def create_song(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        albums_songs = album.song_set.all()
        for s in albums_songs:
            if s.song_title == form.cleaned_data.get("song_title"):
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'You already added that song',
                    'username': request.user.get_username(),
                }
                return render(request, 'music/create_song.html', context)
        song = form.save(commit=False)
        song.album = album
        song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'album': album,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
                'username': request.user.get_username(),
            }
            return render(request, 'music/create_song.html', context)

        song.save()
        return render(request, 'music/detail.html', {'album': album,
                                                     'username': request.user.get_username(), })
    context = {
        'album': album,
        'form': form,
        'username': request.user.get_username(),
    }
    return render(request, 'music/create_song.html', context)


# class SongCreate(CreateView):
#     model = Song
#     fields = ['artist','album_title','genre','album_logo']


class SongDelete(DeleteView):
    model = Song
    success_url = reverse_lazy('music:index')


# funciones de favoritear

def favorite(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    try:
        if song.is_favority:
            song.is_favority = False
        else:
            song.is_favority = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return redirect('http://127.0.0.1:8000/' + str(song.album.pk))
    else:
        return redirect('http://127.0.0.1:8000/' + str(song.album.pk))


def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()
    except (KeyError, Album.DoesNotExist):
        return redirect('music:index')
    else:
        return redirect('music:index')

templates/music/album_form.html
{% extends "base.html" %}
{% block title %}Agregar nuevo álbum{% endblock %}
{% block albums_active %}active{% endblock %}
{% block content %}

<div class="container" style="margin-bottom: 150px;">
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include "music/form-template.html" %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submi" class="btn btn-success">Subir</button>
              </div>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

templates/music/config.html
{% extends "base.html" %}
{% block content %}  
  <div class="container" style="margin-bottom: 150px;">
  <div class='row'>
<div class='col-sm-6 col-sm-offset-1'>
      <form>
        <div class="form-group">
          <label for="inputArtist">Nombre de usuario</label>
          <input type="text" class="form-control" id="inputArtist" maxlength="60" required>
        </div>
        <div class="form-group">
          <label for="albumTitle">Correo electrónico</label>
          <input type="text" class="form-control" id="albumTitle" maxlength="60" required>
        </div>
        <div class="form-group">
          <label for="actualPass" class="text-muted">Contraseña actual</label>
          <input type="password" class="form-control" id="actualPass" maxlength="60" required>
        </div>
        <div class="form-group">
          <label for="newPass" class="text-muted">Nueva contraseña</label>
          <input type="password" class="form-control" id="newPass" maxlength="60" required>
        </div>
        <div class="form-group">
          <label for="confirmPass" class="text-muted">Confirmar contraseña</label>
          <input type="password" class="form-control" id="confirmPass" maxlength="60" required>
        </div>
        <button class="btn btn-lg btn-primary" type="submit">Guardar cambios</button>
      </form>
    </div>
    </div>
    </div>
{% endblock %}

templates/music/create_song.html
{% extends 'base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block content %}
<div class="container" style="margin-bottom: 150px;">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'music:detail' album.id %}">
                            {% if album.album_logo %}
                            <center>
                              <img src="{{ album.album_logo.url }}" class="img-responsive"
                              style="min-width: 220px; max-width: 220px; max-height: 220px; min-height: 220px;">
                              </center>
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h2>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h3>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'music:detail' album.id %}">Visualizar todo</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:create_song' album.id %}">Agregar nueva canción</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Agregar nueva canción</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">

                        {% for field in form  %}
                          <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                              <samp class="text-danger small">{{ field.errors }}</samp>
                            </div>
                            <label class="control-label col-sm-2">{{ field.label_tag }}</label><!--{{ field.label_tag }}-->
                            <div class="col-sm-10">{{ field }}</div>
                          </div>
                        {% endfor %}


                        {# {% include 'form_template.html' %}#}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Subir</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

templates/music/detail.html
{% extends "base.html" %}
{% block title %}Detalles de álbum{% endblock %}
{% block songF %}active{% endblock %}
{% load staticfiles %}
{% block content %}

{% for song in album.song_set.all %}
<Audio id="{{ song.audio_file.url }}" ontimeupdate="timeFunct('{{ song.audio_file.url }}')" preload="none">
  <source src="{{ song.audio_file.url }}" type="audio/mp3">
</Audio>
{% endfor %}

<div class="container" style="margin-bottom: 150px;">
<div class="row">

      <!-- Left Album Info -->
  <div class="col-sm-4 col-md-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <a href="#">
          {% if album.album_logo %}
          <center>
            <img src="{{ album.album_logo.url }}" class="img-responsive"
            style="min-width: 220px; max-width: 220px; max-height: 220px; min-height: 220px;">
            </center>
          {% else %}
            <h3>No hay imagen pra mostrar</h3>
          {% endif %}
        </a>
        <h2>{{ album.album_title }}  <small>{{ album.genre }}</small></h2>
        <h3>{{ album.artist }}</h3>
      </div>
    </div>
  </div>

      <!-- Right Song Info -->
  <div class="col-sm-8 col-md-9">
    <ul class="nav nav-pills" style="margin-bottom: 10px;">
      <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">Visualizar todo</a></li>
      {% if user == album.user %}

        <li role="presentation"><a href="{% url 'music:create_song' album.id %}">Agregar nueva canción</a></li>

      {% endif %}
    </ul>

    <div class="panel panel-default">
      <div class="panel-body">
        <h3>Lista de reproducción</h3>
        {% if error_message %}
          <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <table class="table">
          <thead>
            <tr>
              <th> </th>
              <th>Título</th>
              <th>Favorito</th>
              {% if user == album.user %}
              <th>Eliminar</th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for song in album.song_set.all %}
              <tr>
                <td>
                    <button id="list_play" type="button" class="btn btn-link btn-xs" style="text-decoration: none;" onclick="play_funct_aux('{{ song.audio_file.url }}', '{{ album.album_logo.url }}', '{% static 'img/album.png' %}', '{{ song.song_title }}', '{{ song.album.artist }}', '{{ song.album.album_title }}')">
                      <span class="glyphicon glyphicon-play" style="color: #222;"></span>
                    </button>
                </td>
                <td>{{ song.song_title }}</td>
                <td>
                  <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon {% if song.is_favority %}glyphicon-heart{% else %}glyphicon-heart-empty{% endif %}" style="color:  #222;"></span></a>
                </td>
                <td>
                  {% if user == album.user %}
                  <form action="{% url 'music:song-delete' album.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="song_id" value="{{ song.id }}" />
                    <button type="submit" class="btn btn-link btn-xs" >
                        <span class="glyphicon glyphicon-trash" style="color: #8A0808;"></span>
                    </button>
                  </form>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

templates/music/form-template.html
{% for field in form  %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <samp class="text-danger small">{{ field.errors }}</samp>
    </div>
   <label class="control-label col-sm-2">{{ field.label_tag }}</label>

    <div class="col-sm-10">{{ field }}</div>
  </div>
{% endfor %}

templates/music/index.html
{% extends "base.html" %}
{% block cdF %}active{% endblock %}
{% load staticfiles %}
{% block content %}
{% comment %}
  Album visulitation
{% endcomment %}

{% for song in songs %}
<Audio id="{{ song.audio_file.url }}" ontimeupdate="timeFunct('{{ song.audio_file.url }}')" preload="none">
  <source src="{{ song.audio_file.url }}" type="audio/mp3">
</Audio>
{% endfor %}

<div class="container" style="margin-bottom: 140px;">
  <!--{% if songs %} <h3>Álbumes</h3> {% endif %}-->
  <!--{% if albums%} <h3>Álbumes</h3>{% endif %}-->
    <div class="row">
      {% for album in albums %}
        <a href="{% url 'music:detail' album.id %}" style="display: inline;">
          <div class="col-xs-6 col-sm-4 col-lg-2 placeholder">
            <img class="img-responsive img-rounded" src="{{ album.album_logo.url }}"
            style="min-width: 150px; max-width: 150px; max-height: 150px; min-height: 150px;"/>
              <span class="optionsBar">
                {# funcion para favoritear #}
                <a href="{% url 'music:favorite_album' album.id %}" role="button" style="text-decoration: none;">
                  <button id="heart" class="btn btn-default glyphicon {% if album.is_favorite %}glyphicon-heart{% else %}glyphicon-heart-empty{% endif %}" style="margin-left: 4px;"></button>
                </a>
                {% if album.user == user %}
                    {# funcion para eliminar los albums #}
                <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{ album.id }}"/>
                      <button type="submit" id="trash" class="btn btn-default glyphicon glyphicon-trash"></button>
                </form>

                {% endif %}

                {# funcion para entrar en los detalles del album#}
                <a href="{% url 'music:detail' album.id %}" style="text-decoration: none">
                    <button id="option" class="btn btn-default glyphicon glyphicon-option-horizontal"></button>
                </a>
              </span>
          </div>
      </a>
      
    {% endfor %}
  </div>
  {% if songs %}
<div class="row">
  <!--<div class="col-sm-12">
    <h3>Resultados</h3>
  </div>-->
<div class="col-sm-12">
  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
          <th></th>
          <th>Titulo</th>
          <th>Artista</th>
          <th>Album</th>
          <th>Favorito</th>
          </tr>
        </thead>
        <tbody>
        {% for song in songs %}
          <tr>
          <td>
          <button id="list_play" type="button" class="btn btn-link btn-xs" style="text-decoration: none;" onclick="play_funct_aux('{{ song.audio_file.url }}', '{{ song.album.album_logo.url }}', '{% static 'img/album.png' %}', '{{ song.song_title }}', '{{ song.album.artist }}', '{{ song.album.album_title }}')">
            <span class="glyphicon glyphicon-play" style="color: #222;"></span>
          </button>
          </td>
          <td>{{ song.song_title }}</td>
          <td>{{ song.album.artist }}</td>
          <td>
          <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
            </td>
            <td>
          <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon {% if song.is_favority %}glyphicon-heart{% else %}glyphicon-heart-empty{% endif %}" style="color:  #222;"></span></a>
          {# <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>#}
          </td>
          </tr>
        {% endfor %}
      </tbody>
      </table>
    </div>
  </div>
</div>
</div>
{% endif %}
</div>



{% endblock %}

templates/music/signup.html
  <!DOCTYPE html>
{% load staticfiles %}
<html lang="es">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Music on cloud, streaming, online, cloud, música, nube, escuchar, reproducir, digital, álbum, artista, canción">
    <meta name="description" content="Music on cloud es una plataforma el cual le permite a cualquier usuario distribuir, cooperar y/o promover bocetos musicales propios. Teniendo como prioridad su libre distribución y reproducción de estos mismos vía streming.">
    <meta name="author" content="Music on cloud">
    <link rel="icon" href="{% static "img/icon.ico" %}">

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "font-awesome-4.7.0/css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static 'css/sign.css'%}" rel="stylesheet">

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static 'js/pops.js'%}"></script>

    <title>Regístrate</title>

  </head>

  <body>

  <center>
      <br><br><br>
      <h2 class="form-signin-heading" style="color: #000; ">¡Regístrate ya en Music on Cloud!</h2>
  </center>
{% block content %}

{% endblock %}


  <!--https://www.pexels.com/photo/red-office-yellow-school-40799/-->
  <footer class="footer-distributed" style="position: absolute; top: 0; width: 100%; background: url({% static 'img/colors.jpeg'%}) no-repeat center center fixed; opacity: .8;">
      <div class="container" >
      <center>
        <img style="max-width:90px; margin-bottom: 5px; margin-top: 5px;" src="{% static 'img/logo.png'%}">
        <br>
      </center>
      </div>
    </footer>


  </body>
</html>