UComment/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'UComment'
urlpatterns = [
    url(r'^profile/(?P<slug>\w+)/$', login_required(views.UserView.as_view(), login_url='music:index'), name='user'),
]

music/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'music'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),  # conexion con el index
    url(r'configuration/$', views.ConfigView, name = 'config'),  # pagina de configuracion
#    url(r'signup/$',views.SignView.as_view(),name = 'signup'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view(), login_url='music:index'), name='detail'),  # conexion con el view de detalles del album
    url(r'album/add/$', login_required(views.AlbumCreate.as_view(), login_url='music:index'), name='album-add'),  # creacion de un nuevo album

     #para hacer un update se necesita ir tld/app/album/pk/
    url(r'album/(?P<pk>[0-9]+)/$', login_required(views.AlbumUpdate.as_view(), login_url='music:index'), name='album-update'), #actualizar un album
    url(r'album/(?P<pk>[0-9]+)/delete/$', login_required(views.AlbumDelete.as_view(), login_url='music:index'), name='album-delete'), #eliminar un album entero
    #url(r'register/$',views.RegisterView.as_view(),name='register'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', login_required(views.create_song, login_url='music:index'), name='create_song'), #crear cancion
    url(r'song/(?P<pk>[0-9]+)/delete/$', login_required(views.SongDelete.as_view(), login_url='music:index'), name='song-delete'), #eliminar una cancion
    url(r'^(?P<song_id>[0-9]+)/favorite/$', login_required(views.favorite,login_url='music:index'), name='favorite'),#favoritear un cancion
    url(r'^(?P<album_id>[0-9]+)/favorite_album/$', login_required(views.favorite_album, login_url='music:index'), name='favorite_album'),#favoritear un album
    ]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import privacy, helpi, license

urlpatterns = [
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music.urls')),
    url(r'^', include('UComment.urls')),
    url(r'^privacy/$', privacy, name='privacy'),
    url(r'^help/$', helpi, name='help'),
    url(r'^license/$', license, name='license'),
]

if settings.DEBUG:
    ##urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Music on cloud, streaming, online, cloud, música, nube, escuchar, reproducir, digital, álbum, artista, canción">
    <meta name="description" content="Music on cloud es una plataforma el cual le permite a cualquier usuario distribuir, cooperar y/o promover bocetos musicales propios. Teniendo como prioridad su libre distribución y reproducción de estos mismos vía streming.">
    <meta name="author" content="Music on cloud">
    <link rel="icon" href="{% static "img/icon.ico" %}">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "font-awesome-4.7.0/css/font-awesome.min.css" %}" rel="stylesheet">

    <link href="{% static "css/starter-template.css" %}" rel="stylesheet">
    <link href="{% static "css/media_player.css" %}" rel="stylesheet">
    <link href="{% static "css/slider.css" %}" rel="stylesheet">
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <script src="{% static "js/pops.js" %}"></script>
    <script src="{% static "js/media_player.js" %}"></script>
    <title>{% block title %}Music on Cloud{% endblock %}</title>
</head>

<body>

    {% with request.resolver_match.url_name as url_name %}
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-" >
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar" style="background-color: #fff;"></span>
            <span class="icon-bar" style="background-color: #fff;"></span>
            <span class="icon-bar" style="background-color: #fff;"></span>
          </button>
          <img style="max-width:60px; margin-top: 8px; margin-bottom: 0px; margin-right: 10px; margin-left: 15px" src="{% static "img/logo.png" %}" data-toggle="tooltip" title="Hecho con todo el amor del mundo :)" data-placement="bottom">
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="{% if url_name == 'user' %}active{% endif %}"><a href="{% url 'UComment:user' username %}"><span class="glyphicon glyphicon-user" aria-hidden="true" style="font-size: 25px;" data-toggle="tooltip" title="Perfil" data-placement="bottom"></span></a></li>
            <li class="{% if url_name == 'index' or url_name == 'detail' or url_name == 'create_song' %}active{% endif %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-music" aria-hidden="true" style="font-size: 25px;" data-toggle="tooltip" title="Música" data-placement="bottom"></span></a></li>
            <li class="{% if url_name == 'album-add' %}active{% endif %}"><a href="{% url 'music:album-add' %}"><span class="glyphicon glyphicon-upload" aria-hidden="true" style="font-size: 25px;" data-toggle="tooltip" title="Subir música" data-placement="bottom"></span></a></li>

			<div style="display: inline; float: left;">
		        <form class="navbar-form" role="search" method="get" action="{% url 'music:index' %}">
		        <div class="input-group">
		            <input type="text" class="form-control" placeholder="Buscar" style="background-color: transparent; height: 40px; color: #fff;" name="q" value="{{ request.GET.q }}">
		            <div class="input-group-btn">
		                <button class="btn btn-default" type="submit" style="background-color: transparent;"><i class="glyphicon glyphicon-search" style="color: #fff; font-size: 21px;"></i></button>
		            </div>
		        </div>
		        </form>
		    </div>

          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li class="{% if url_name == 'config' %}active{% endif %}"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog" style="font-size: 25px;" data-toggle="tooltip" title="Configurar" data-placement="bottom"></span></a>
                <ul class="dropdown-menu">
                  <li class="dropdown-header">Cuenta</li>
                    <li><a href="{% url 'music:config' %}">Información</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'auth_logout' %}">Cerrar sesión</a></li>
                  </ul>
              </li>
            </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% endwith %}

    <br></br>



{% block content %}

{% endblock %}

    <footer class="footer-distributed">
      <div class="container">

      <span class="footer-left" style="float: left;">
      	<button id="album_info" data-html="true" class="btn btn-link" data-container="body" data-toggle="popover" data-trigger="focus" data-placement="top" data-content="">
          <img id="album_footer" src="{% static "img/album.png" %}" class="img-responsive img-thumbnail" alt="Demon days" style="width:70px; height: 70px;"></button>
	  </span>

          <center>
	          <!--BOTÓN DEMO-->
	          <button id="backwardBtn" class="btn btn-link" data-container="body" data-toggle="tooltip" title="anterior" data-placement="top"
	          onclick="" aria-hidden="true"><span id="" class="glyphicon glyphicon-step-backward"></span></button>

	          <button id="media_button" class="btn btn-link" data-container="body" data-toggle="tooltip" title="reproducir" data-placement="top"
	          onclick="mediaFunctionsPlus()" aria-hidden="true"><span id="playButton" class="glyphicon glyphicon-play"></span></button>

	          <!--BOTÓN DEMO-->
	          <button id="forwardBtn" class="btn btn-link" data-container="body" data-toggle="tooltip" title="siguiente" data-placement="top"
	          onclick="" aria-hidden="true"><span id="" class="glyphicon glyphicon-step-forward"></span></button>

	          <button id='vol_btn' class="btn btn-link" data-container="body" data-placement="top" aria-hidden="true" onclick="getVol()">
	          	<span id="volume_button" class="glyphicon glyphicon-volume-up"></span>
	          </button>
			  <span id="vol_popover" style="display: none;"><input id='slider_vol' type='range' min='0' max='10' step='1' value='' style='width: 100px; transform: rotate(270deg); padding-top: 50px; padding-bottom: 50px;' onchange='vol(this.value);'></input></span>

        		<br>
		      <span id="tracktime" style="font-size: 14px;">00:00</span>
		      	<span><input id="slider_time" type="range" min="0" max="0" step="1" value="0"></input></span>
		      <span id="tracktimeOrigin" style="font-size: 14px;">00:00</span>
	      </center>

      </div>
    </footer>
</body>

</html>

templates/base1.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Music on cloud, streaming, online, cloud, música, nube, escuchar, reproducir, digital, álbum, artista, canción">
    <meta name="description" content="Music on cloud es una plataforma el cual le permite a cualquier usuario distribuir, cooperar y/o promover bocetos musicales propios. Teniendo como prioridad su libre distribución y reproducción de estos mismos vía streming.">
    <meta name="author" content="Music on cloud">
    <link rel="icon" href="{% static "img/icon.ico" %}">

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "font-awesome-4.7.0/css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "css/footer-distributed.css"%}" rel="stylesheet">
    <link href="{% static "css/sign.css"%}" rel="stylesheet">

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/pops.js" %}"></script>

    <title>Music on cloud</title>

  </head>

  <body>

  <center>
      <img src="{% static "img/logo.png" %}" data-toggle="tooltip" title="Hecho con todo el amor del mundo." data-placement="bottom">
      <h2 class="form-signin-heading" style="color: #fff; ">¡Comparte tus bocetos musicales!</h2>
  </center>

  <div class="container" style="margin-bottom: 100px;">
        <form class="form-signin" method="POST" autocomplete="off" action="{% url "auth_login" %}">{% csrf_token %}
        <input type="text" id="inputUser" class="form-control" name="username" placeholder="Usuario" maxlength="50" required autofocus>
        <input type="password" id="inputPassword" class="form-control" name="password" placeholder="Contraseña" maxlength="50" required>
        <center><a href="{% url 'auth_password_reset' %}">¿Olvidaste tu contraseña?</a></center>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button><br>
      <p style="color: #fff">¿Aún no tienes cuenta? Regístrate <b><a href="{% url 'registration_register' %}" style="font-size: 18px">¡aquí!</a></b></p>
  		</form>
   </div>



  <footer class="footer-distributed">
      <div class="container" >
        <p class="pull-right">
        <br>
      <a class="btn btn-social-icon btn-xs btn-twitter" href="#" title="Twitter"><span class="fa fa-twitter" style="font-size: 25px;"></span></a>
      <a class="btn btn-social-icon btn-xs btn-vimeo" href="#" title="Vimeo"><span class="fa fa-vimeo" style="font-size: 25px;"></span></a>
      <a class="btn btn-social-icon btn-xs btn-gitlab" href="https://gitlab.com/Technovasoft/Django-Music" title="Gitlab"><span class="fa fa-gitlab" style="font-size: 25px;"></span></a>
        <p><br>&copy; 2017 Music on cloud &middot; <a href="{% url 'license' %}">Licencia</a> &middot; <a href="{% url 'privacy' %}">Política de privacidad</a> &middot; <a href="{% url 'help' %}">Ayuda</a></p>
      </div>
    </footer>


  </body>
</html>

templates/baseSig.html
  <!DOCTYPE html>
{% load staticfiles %}
<html lang="es">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Music on cloud, streaming, online, cloud, música, nube, escuchar, reproducir, digital, álbum, artista, canción">
    <meta name="description" content="Music on cloud es una plataforma el cual le permite a cualquier usuario distribuir, cooperar y/o promover bocetos musicales propios. Teniendo como prioridad su libre distribución y reproducción de estos mismos vía streming.">
    <meta name="author" content="Music on cloud">
    <link rel="icon" href="{% static "img/icon.ico" %}">

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "font-awesome-4.7.0/css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static 'css/sign.css'%}" rel="stylesheet">

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static 'js/pops.js'%}"></script>

    <title>Regístrate</title>

  </head>

  <body>

  <center>
      <br><br><br>

  </center>
  
{% block content %}

{% endblock %}


  <!--https://www.pexels.com/photo/red-office-yellow-school-40799/-->
  <footer class="footer-distributed" style="position: absolute; top: 0; width: 100%; background: url({% static 'img/colors.jpeg'%}) no-repeat center center fixed; opacity: .8;">
      <div class="container" >
      <center>
        <img style="max-width:90px; margin-bottom: 5px; margin-top: 5px;" src="{% static 'img/logo.png'%}">
        <br>
      </center>
      </div>
    </footer>


  </body>
</html>

templates/help.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Music on cloud, streaming, online, cloud, música, nube, escuchar, reproducir, digital, álbum, artista, canción">
    <meta name="description" content="Music on cloud es una plataforma el cual le permite a cualquier usuario distribuir, cooperar y/o promover bocetos musicales propios. Teniendo como prioridad su libre distribución y reproducción de estos mismos vía streming.">
    <meta name="author" content="Music on cloud">
    <link rel="icon" href="{% static "img/icon.ico" %}">

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "font-awesome-4.7.0/css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static 'css/sign.css' %}" rel="stylesheet">

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static 'js/pops.js' %}"></script>

    <title>Ayuda</title>

  </head>

  <body>

  <br><br>

<div class="container" style="margin-bottom: 10px;">
<div class="col-md-9">
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          ¿Qué es <b>Music on cloud</b>?
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
      <b>Music on cloud</b> es una plataforma donde el usuario puede distribuir y promocionar sus proyectos musicales de forma gratuita e ilimitada mediante una suscripción.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          ¿Qué licencia adquiere <b>mi material</b> al ser subido?
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        El contenido subido a la plataforma adquiere automáticamente una licencia <i><b>Creative Commons</b></i>, con el fin de proteger los proyectos musicales de todos los usuarios.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          ¿Cuáles son las <b>ventajas</b> de usar este servicio?
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        Actualmente existen muchas plataformas que ofrecen música. Lamentablemente todas ellas son privativas, ¿Qué quiere decir? que todo el contenido que se sube a las plataformas deben estar afiliados a una disquera, que desafortunadamente tiene una comisión muy alta y adquieren todos los derechos de los proyectos, limitando así la libre distribución y dejando la industria musical sólo para unos cuantos.<br>
        Además de que tales plataformas no son de código abierto y además de ser necesaria una suscripción mensual o anual para su uso.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          ¿Es necesario estar afiliado a una <b>disquera</b>?
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
        No.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFive">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          ¿Por qué son tan <b>guapos</b>?
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
      <div class="panel-body">
        Porque así nacimos.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFive">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          ¿Por qué el contenido esta en <b>español</b>?
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
      <div class="panel-body">
        El contenido de esta página se encuentra en español ya que quisimos tener impacto primeramente en México y América latina.
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSix">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
          ¿Puedo subir cualquier contenido?
        </a>
      </h4>
    </div>
    <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
      <div class="panel-body">
        Lametablemente no.<br>Una vez subido tu nuevo álbum, éste será analizado para comprobar que no este sujeto a derechos de autor. En caso que de que no contenga, será público y podrás comenzar a adjuntar las canciones a este mismo.<br>En caso de que estas canciones estén sujetas a derechos de autor, procederemos inmediatamente a borrar el contenido de tu perfil sin aviso previo.
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSeven">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
          ¿En qué casos se daría de baja mi cuenta?
        </a>
      </h4>
    </div>
    <div id="collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEight">
      <div class="panel-body">
        Si se llega a sumar el total de tres reportes por violación a derechos de autor, o cualquier otro uso indebido de esta plataforma.
      </div>
    </div>
  </div>

</div>
</div>
</div>



  <!--https://www.pexels.com/photo/red-office-yellow-school-40799/-->
  <footer class="footer-distributed" style="position: absolute; top: 0; width: 100%; background: url({% static 'img/colors.jpeg' %}) no-repeat center center fixed; opacity: .8;">
      <div class="container" >
      <center>
        <img style="max-width:90px; margin-bottom: 5px; margin-top: 5px;" src="{% static 'img/logo.png' %}">
        <br>
      </center>
      </div>
    </footer>


  </body>
</html>